---


- name: remove APT lock
  file:
    path: /var/lib/dpkg/lock
    state: absent
  tags:
    - prep
    - apt

- name: install prereq packages
  apt:
    name: bind9, bind9utils, dnsutils
    state: present
    update_cache: yes
  tags:
  - prep
