---


- name: remove APT lock
  file:
    path: /var/lib/dpkg/lock
    state: absent
  tags:
    - prep
    - apt


- name: apt-get update
  apt:
    update_cache: yes
  tags:
    - prep
    - apt


- name: install prereq packages
  apt:
    pkg:
    - bind9
    - bind9utils
    - dnsutils
    state: present
    update_cache: yes
  tags:
  - prep